INSERT INTO OWNER (ID, NAME) values (100,'ECE SAGLAM');
INSERT INTO OWNER (ID, NAME) values (200,'BERKE DEMIR');
INSERT INTO PET (ID, BREED, OWNER_ID) VALUES (301,'British Shorthair Cat',100);
INSERT INTO PET (ID, BREED, OWNER_ID) VALUES (302,'African Grey Parrot',100);
INSERT INTO PET (ID, BREED, OWNER_ID) VALUES (303,'Labrador',200);
INSERT INTO PET (ID, BREED, OWNER_ID) VALUES (304,'Birman Cat',200);
